---
- name: Update apt
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes

- name: Install Docker Compose plugin
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes

- name: Verify Docker Compose installation
  command: docker compose version
  register: compose_version

- debug:
    msg: "Docker Compose установлен: {{ compose_version.stdout }}"