plugin: amazon.aws.aws_ec2

regions:
  - eu-central-1

filters:
  tag:Name: diploma-app
  instance-state-name: running

# ansible_host = публичный IP, чтобы подключался не к приватному DNS
compose:
  ansible_host: public_ip_address
  ansible_user: "'ubuntu'"

groups:
  app: "tags.Name is defined and tags.Name == 'diploma-app'"

strict: false