plugin: amazon.aws.aws_ec2   # <— исправлено (было amazon.aws.ec2)

regions:
  - eu-central-1

filters:
  tag:Name: diploma-app
  instance-state-name: running

hostnames:
  - public-ip-address

compose:
  ansible_user: "'ubuntu'"
  ansible_ssh_private_key_file: "~/.ssh/ssh-diploma-key.pem"

strict: false